### ISSUE TITLE
How to install autoattack?

### ISSUE THREAD

**Issue by SensenGao** [lionel-w2/FAP#1]
I encountered an issue where I couldn't install the `autoattack` module. I used the same PyTorch version as yours to configure Dassl, but when I tried to install the required `autoattack` module, the installation failed. Could you provide a more detailed tutorial for setting up the environment?
![image](https://github.com/user-attachments/assets/5b938277-b0bf-4e47-a40f-df9269717603)

**Comment by SensenGao** [comment]
I got the solution from https://github.com/TreeLLi/APT/blob/main/requirements.txt. We should use git+https://github.com/fra31/auto-attack to install.

**Comment by qmechlab** [comment]
Is your loss output correct? My output is the nan value.

**Comment by qmechlab** [comment]
By the way, what versions of Python and pytorch are you using?

**Comment by SensenGao** [comment]
I use python=3.8, pytorch=1.10.1

**Comment by qmechlab** [comment]
Thanks for your reply, I reinstalled the environment as you said and it solved the problem.
